ZMI: fixed html
perfact/ZPsycopgDA pull request #9
Opened 2020-12-14 20:48 UTC by drfho

Hi @jhinghaus,
excuse me there were still some html problems and the check-values of dbconn were not properly stored. I fixed that now.
Thank your for the patience
f

2020-12-21 07:34 UTC, jhinghaus requested changes

2020-12-21 07:34 UTC, jhinghaus commented on Products/ZPsycopgDA/dtml/add.dtml
> +        <input class="btn btn-primary" type="checkbox" id="check" name="check" value="YES" />
Did you remove the default checkmark on purpose?

2020-12-21 07:34 UTC, jhinghaus commented on Products/ZPsycopgDA/dtml/add.dtml
> +        <input class="btn btn-primary" type="checkbox" id="autocommit" name="autocommit" value="YES" checked="selected" />
`checked="checked"` would look better on a checkbox.

2020-12-21 07:34 UTC, jhinghaus commented on Products/ZPsycopgDA/dtml/add.dtml
> +        <input class="btn btn-primary" type="checkbox" id="readonlymode" name="readonlymode" value="YES" checked="selected" />
See above.

2021-03-10 14:28 UTC, jan-jockusch commented
@drfho Thanks for the PR! In the mean time, we had other problems with the UI, which prompted https://github.com/perfact/ZPsycopgDA/pull/12.

I took the liberty of incorporating your improvements there.

2021-03-10 18:11 UTC, drfho commented
Great! 
Thanks
fh

2021-03-12 08:46 UTC, jan-jockusch commented
This has been merged as part of https://github.com/perfact/ZPsycopgDA/pull/12, so closing.

2021-03-12 08:46 UTC, closed without merging